name: .NET Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore src/Auto.API/Auto.API.csproj

    - name: Build
      run: dotnet build src/Auto.API/Auto.API.csproj --configuration Release --no-restore

    # - name: Run tests
    #   run: dotnet test --no-restore --verbosity normal
